import { Client } from "pg";

const EMBED_MODEL = "@cf/baai/bge-m3";
const RERANK_MODEL = "@cf/baai/bge-reranker-base";
const NOTE_META_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";

type JsonRecord = Record<string, unknown>;

export interface Env {
  AI: Ai;
  TEXT_DOCS: VectorizeIndex;
  HYPERDRIVE: Hyperdrive;
  VPC_SERVICE?: Fetcher;
  DEFAULT_NAMESPACE_ID?: string;
  DEFAULT_VECTOR_LIMIT?: string;
  DEFAULT_RESULT_LIMIT?: string;
  DEFAULT_MIN_RERANK_SCORE?: string;
  NBSS_BASE_URL?: string;
  ENABLE_NBSS_HYDRATE?: string;
}

interface EmbeddingResponse {
  data: number[][];
}

interface RerankItem {
  id?: number;
  score?: number;
  text?: string;
}

interface RerankResponse {
  response?: RerankItem[];
}

interface SearchRequest {
  query?: string;
  namespaceId?: string;
  vectorLimit?: number;
  limit?: number;
  page?: number;
  minRerankScore?: number;
  bodyMode?: "all" | "inline" | "nbss";
  hydrateBody?: boolean;
  tags?: string[];
}

interface RecentRequest {
  namespaceId?: string;
  limit?: number;
  cursor?: string;
  tags?: string[];
}

interface DetailRequest {
  namespaceId?: string;
  hydrateBody?: boolean;
}

interface CreateRequest {
  namespaceId?: string;
  title?: string;
  body?: string;
}

interface AutoCreateRequest {
  namespaceId?: string;
  body?: string;
}

interface TextDocMeta {
  createdAt?: string;
  docKind?: string;
  sourceType?: string;
  title?: string;
  sourceId?: string;
  tags?: string[];
  autoGenerated?: boolean;
}

interface TextDocMetadata {
  text?: string;
  namespaceId?: string;
  nbssfid?: string;
  meta?: TextDocMeta;
}

interface SearchItem {
  id: string;
  score: number | null;
  rerankScore: number | null;
  namespaceId: string;
  text: string;
  bodyText?: string;
  bodySource?: "inline" | "nbss";
  nbssfid: string;
  meta: TextDocMeta;
}

type BodyMode = "all" | "inline" | "nbss";

interface DetailItem {
  id: string;
  namespaceId: string;
  text: string;
  bodyText: string;
  bodySource: "inline" | "nbss";
  nbssfid: string;
  meta: TextDocMeta;
}

interface RecentItem {
  id: string;
  namespaceId: string;
  text: string;
  nbssfid: string;
  meta: TextDocMeta;
}

type VectorMatch = {
  id: string;
  score?: number;
  metadata?: unknown;
};

interface TextGenerationResponse {
  response?: string;
}

interface GeneratedNoteMeta {
  title?: string;
  tags?: unknown;
}

interface RecentCursor {
  createdAt: string;
  id: string;
}

type RecentNoteRow = {
  id: string;
  namespace_id: string;
  text_preview: string;
  nbssfid: string;
  created_at: string | Date;
  source_type: string;
  title: string;
  tags: unknown;
  auto_generated: boolean | null;
};

let recentNotesSchemaReady = false;

function json(status: number, payload: JsonRecord): Response {
  return new Response(JSON.stringify(payload, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store"
    }
  });
}

function asPositiveInt(value: unknown, fallback: number, max: number): number {
  const n = Number(value);
  if (!Number.isFinite(n) || n <= 0) {
    return fallback;
  }
  return Math.min(Math.floor(n), max);
}

function asNonNegativeNumber(value: unknown, fallback: number): number {
  const n = Number(value);
  if (!Number.isFinite(n) || n < 0) {
    return fallback;
  }
  return n;
}

function asTrimmedString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

function isTruthy(value: string | undefined): boolean {
  return value === "1" || value === "true" || value === "yes";
}

async function readJson<T>(request: Request): Promise<T | null> {
  try {
    return (await request.json()) as T;
  } catch {
    return null;
  }
}

async function embedQuery(query: string, env: Env): Promise<number[]> {
  const result = (await env.AI.run(EMBED_MODEL, { text: [query] })) as EmbeddingResponse;
  const vector = result?.data?.[0];
  if (!Array.isArray(vector) || vector.length === 0) {
    throw new Error("embedding_failed");
  }
  return vector;
}

async function embedText(text: string, env: Env): Promise<number[]> {
  const result = (await env.AI.run(EMBED_MODEL, { text: [text] })) as EmbeddingResponse;
  const vector = result?.data?.[0];
  if (!Array.isArray(vector) || vector.length === 0) {
    throw new Error("embedding_failed");
  }
  return vector;
}

function encodeCursor(cursor: RecentCursor): string {
  return btoa(JSON.stringify(cursor));
}

function decodeCursor(value: string | null): RecentCursor | null {
  if (!value) {
    return null;
  }
  try {
    const parsed = JSON.parse(atob(value)) as RecentCursor;
    if (!asTrimmedString(parsed?.createdAt) || !asTrimmedString(parsed?.id)) {
      return null;
    }
    return {
      createdAt: asTrimmedString(parsed.createdAt),
      id: asTrimmedString(parsed.id)
    };
  } catch {
    return null;
  }
}

function generateNoteId(): string {
  const bytes = new Uint8Array(12);
  crypto.getRandomValues(bytes);
  return `note_${Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("")}`;
}

function normalizeWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function stripEdgePunctuation(value: string): string {
  return value.replace(/^[\s"'`“”‘’()[\]{}<>,.;:!?/\\|+-]+/, "").replace(/[\s"'`“”‘’()[\]{}<>,.;:!?/\\|+-]+$/, "");
}

function sanitizeTag(raw: string): string {
  return stripEdgePunctuation(normalizeWhitespace(raw)).slice(0, 24);
}

function sanitizeTags(tags: unknown): string[] {
  const blocked = new Set(["笔记", "记录", "内容", "文本", "想法", "随想", "note", "notes", "text", "content"]);
  const seen = new Set<string>();
  const output: string[] = [];
  for (const raw of asStringArray(tags)) {
    const tag = sanitizeTag(raw);
    const key = tag.toLocaleLowerCase("zh-CN");
    if (!tag || tag.length < 2 || blocked.has(key) || seen.has(key)) {
      continue;
    }
    seen.add(key);
    output.push(tag);
    if (output.length >= 10) {
      break;
    }
  }
  return output;
}

function asBoolean(value: unknown): boolean {
  return value === true || value === "true" || value === 1;
}

function mapRecentRow(row: RecentNoteRow): RecentItem {
  const createdAt = row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at);
  return {
    id: row.id,
    namespaceId: row.namespace_id,
    text: row.text_preview ?? "",
    nbssfid: row.nbssfid ?? "",
    meta: {
      createdAt,
      docKind: "raw_text",
      sourceType: row.source_type ?? "",
      title: row.title ?? "",
      sourceId: row.id,
      tags: sanitizeTags(row.tags),
      autoGenerated: asBoolean(row.auto_generated)
    }
  };
}

async function generateAutoNoteMeta(body: string, env: Env): Promise<{ title: string; tags: string[] }> {
  const prompt = [
    "你是一个笔记元信息生成器。基于用户提供的笔记正文，输出 JSON。",
    "要求：",
    "1. 生成一个简洁、中性的标题，不要写成完整摘要句，不要带引号。",
    "2. 标题必须尽量贴近正文原词，不要引入正文里没有的新概念，不要做上位概括或目的推断。",
    "3. 如果正文像清单、待办、会议记录、材料整理，标题要保留这种文本类型，不要改写成解释性标题。",
    "4. 禁止把具体事项抽象成更泛的意图。例如不要把购物清单写成晚餐计划。",
    "5. 标签用于检索分类，优先主题词、实体词、任务词、领域词。",
    "6. 生成 3 到 8 个标签，最多 10 个。",
    "7. 禁止输出空泛标签，例如：笔记、记录、内容、想法、文本、note。",
    "8. 不要输出解释，只输出 JSON 对象，格式为 {\"title\":\"...\",\"tags\":[...]}。",
    "",
    "正文：",
    body
  ].join("\n");

  const result = await env.AI.run(NOTE_META_MODEL, {
    prompt,
    response_format: { type: "json_object" }
  }) as TextGenerationResponse;
  const parsed = JSON.parse(String(result.response ?? "{}")) as GeneratedNoteMeta;
  const title = stripEdgePunctuation(normalizeWhitespace(asTrimmedString(parsed.title))).slice(0, 80);
  const tags = sanitizeTags(parsed.tags);
  if (!title) {
    throw new Error("auto_title_generation_failed");
  }
  if (!tags.length) {
    throw new Error("auto_tags_generation_failed");
  }
  return { title, tags };
}

function utf8Bytes(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

function truncateUtf8Text(text: string, maxBytes: number): string {
  if (utf8Bytes(text).byteLength <= maxBytes) {
    return text;
  }
  let low = 0;
  let high = text.length;
  while (low < high) {
    const mid = Math.ceil((low + high) / 2);
    const candidate = text.slice(0, mid);
    if (utf8Bytes(candidate).byteLength <= maxBytes) {
      low = mid;
    } else {
      high = mid - 1;
    }
  }
  return text.slice(0, low).trimEnd();
}

function normalizeMetadata(input: unknown): TextDocMetadata {
  if (!input || typeof input !== "object") {
    return {};
  }
  const record = input as JsonRecord;
  const metaValue = record.meta;
  const meta = metaValue && typeof metaValue === "object" ? (metaValue as TextDocMeta) : {};
  return {
    text: typeof record.text === "string" ? record.text : "",
    namespaceId: typeof record.namespaceId === "string" ? record.namespaceId : "",
    nbssfid: typeof record.nbssfid === "string" ? record.nbssfid : "",
    meta
  };
}

async function queryVectorize(
  queryVector: number[],
  namespaceId: string,
  vectorLimit: number,
  env: Env
): Promise<VectorMatch[]> {
  const result = await env.TEXT_DOCS.query(queryVector, {
    topK: vectorLimit,
    returnMetadata: "all" as const
  });
  return ((result.matches ?? []) as VectorMatch[]).filter((item) => {
    const metadata = normalizeMetadata(item.metadata);
    return metadata.namespaceId === namespaceId;
  });
}

function buildRerankContext(match: VectorMatch): string {
  const metadata = normalizeMetadata(match.metadata);
  const title = metadata.meta?.title?.trim() ?? "";
  const text = metadata.text?.trim() ?? "";
  if (title && text) {
    return `${title}\n\n${text}`;
  }
  return title || text || match.id;
}

async function rerankMatches(query: string, matches: VectorMatch[], limit: number, env: Env): Promise<SearchItem[]> {
  if (matches.length === 0) {
    return [];
  }
  const contexts = matches.map(buildRerankContext);
  const rerank = (await env.AI.run(RERANK_MODEL, {
    query,
    contexts: contexts.map((text) => ({ text }))
  })) as RerankResponse;

  const ranked = (rerank.response ?? [])
    .filter((item) => typeof item.id === "number" && item.id >= 0 && item.id < matches.length)
    .sort((left, right) => (Number(right.score ?? 0) - Number(left.score ?? 0)));

  const output: SearchItem[] = [];
  for (const item of ranked.slice(0, limit)) {
    const match = matches[item.id as number];
    const metadata = normalizeMetadata(match.metadata);
    output.push({
      id: match.id,
      score: typeof match.score === "number" ? match.score : null,
      rerankScore: typeof item.score === "number" ? item.score : null,
      namespaceId: metadata.namespaceId ?? "",
      text: metadata.text ?? "",
      nbssfid: metadata.nbssfid ?? "",
      meta: metadata.meta ?? {}
    });
  }
  return output;
}

function matchesBodyMode(item: SearchItem, bodyMode: BodyMode): boolean {
  if (bodyMode === "inline") {
    return !item.nbssfid;
  }
  if (bodyMode === "nbss") {
    return Boolean(item.nbssfid);
  }
  return true;
}

function matchesTags(item: SearchItem, tags: string[]): boolean {
  if (!tags.length) {
    return true;
  }
  const itemTags = sanitizeTags(item.meta?.tags).map((tag) => tag.toLocaleLowerCase("zh-CN"));
  if (!itemTags.length) {
    return false;
  }
  return tags.every((tag) => itemTags.includes(tag.toLocaleLowerCase("zh-CN")));
}

async function maybeHydrateBody(items: SearchItem[], hydrateBody: boolean, env: Env): Promise<void> {
  if (!hydrateBody || !isTruthy(env.ENABLE_NBSS_HYDRATE)) {
    for (const item of items) {
      item.bodyText = item.text;
      item.bodySource = "inline";
    }
    return;
  }
  for (const item of items) {
    if (!item.nbssfid) {
      item.bodyText = item.text;
      item.bodySource = "inline";
      continue;
    }
    try {
      const response = await fetchNbssObject(item.nbssfid, env);
      if (!response.ok) {
        throw new Error(`nbss_http_${response.status}`);
      }
      item.bodyText = await response.text();
      item.bodySource = "nbss";
    } catch (error) {
      console.error("nbss hydrate failed", {
        id: item.id,
        nbssfid: item.nbssfid,
        error: error instanceof Error ? error.message : String(error)
      });
      throw new Error(`nbss_hydrate_failed:${item.id}`);
    }
  }
}

async function withPgClient<T>(env: Env, fn: (client: Client) => Promise<T>): Promise<T> {
  const client = new Client({
    connectionString: env.HYPERDRIVE.connectionString
  });
  await client.connect();
  try {
    if (!recentNotesSchemaReady) {
      await client.query(`
        CREATE TABLE IF NOT EXISTS recent_notes (
          id TEXT PRIMARY KEY,
          namespace_id TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL,
          title TEXT NOT NULL,
          text_preview TEXT NOT NULL,
          source_type TEXT NOT NULL,
          tags JSONB NOT NULL DEFAULT '[]'::jsonb,
          nbssfid TEXT NOT NULL DEFAULT '',
          auto_generated BOOLEAN NOT NULL DEFAULT FALSE
        );
      `);
      await client.query(`
        CREATE INDEX IF NOT EXISTS recent_notes_namespace_created_idx
        ON recent_notes (namespace_id, created_at DESC, id DESC);
      `);
      recentNotesSchemaReady = true;
    }
    return await fn(client);
  } finally {
    await client.end();
  }
}

async function indexRecentNote(item: DetailItem, env: Env): Promise<void> {
  await withPgClient(env, async (client) => {
    await client.query(
      `
        INSERT INTO recent_notes (
          id,
          namespace_id,
          created_at,
          title,
          text_preview,
          source_type,
          tags,
          nbssfid,
          auto_generated
        )
        VALUES ($1, $2, $3::timestamptz, $4, $5, $6, $7::jsonb, $8, $9)
        ON CONFLICT (id) DO UPDATE SET
          namespace_id = EXCLUDED.namespace_id,
          created_at = EXCLUDED.created_at,
          title = EXCLUDED.title,
          text_preview = EXCLUDED.text_preview,
          source_type = EXCLUDED.source_type,
          tags = EXCLUDED.tags,
          nbssfid = EXCLUDED.nbssfid,
          auto_generated = EXCLUDED.auto_generated
      `,
      [
        item.id,
        item.namespaceId,
        item.meta.createdAt ?? new Date().toISOString(),
        item.meta.title ?? item.id,
        item.text ?? "",
        item.meta.sourceType ?? "",
        JSON.stringify(item.meta.tags ?? []),
        item.nbssfid ?? "",
        item.meta.autoGenerated ?? false
      ]
    );
  });
}

async function listRecentNotes(request: RecentRequest, env: Env): Promise<{
  items: RecentItem[];
  hasMore: boolean;
  nextCursor: string | null;
  limit: number;
  tags: string[];
}> {
  const namespaceId = asTrimmedString(request.namespaceId ?? env.DEFAULT_NAMESPACE_ID);
  if (!namespaceId) {
    throw new Error("missing_namespace_id");
  }
  const limit = asPositiveInt(request.limit ?? env.DEFAULT_RESULT_LIMIT ?? 20, 20, 50);
  const cursor = decodeCursor(asTrimmedString(request.cursor));
  if (request.cursor && !cursor) {
    throw new Error("invalid_cursor");
  }
  const tags = sanitizeTags(request.tags);

  return withPgClient(env, async (client) => {
    const values: unknown[] = [namespaceId];
    let sql = `
      SELECT id, namespace_id, text_preview, nbssfid, created_at, source_type, title, tags, auto_generated
      FROM recent_notes
      WHERE namespace_id = $1
    `;

    if (cursor) {
      values.push(cursor.createdAt, cursor.id);
      sql += ` AND (created_at, id) < ($${values.length - 1}::timestamptz, $${values.length}::text)`;
    }

    if (tags.length) {
      values.push(tags);
      sql += ` AND tags ?& $${values.length}::text[]`;
    }

    values.push(limit + 1);
    sql += ` ORDER BY created_at DESC, id DESC LIMIT $${values.length}`;

    const result = await client.query<RecentNoteRow>(sql, values);

    const rows = result.rows.slice(0, limit);
    const items = rows.map(mapRecentRow);
    const hasMore = result.rows.length > limit;
    const last = rows.at(-1);
    const nextCursor = hasMore && last
      ? encodeCursor({
          createdAt: last.created_at instanceof Date ? last.created_at.toISOString() : String(last.created_at),
          id: last.id
        })
      : null;

    return {
      items,
      hasMore,
      nextCursor,
      limit,
      tags
    };
  });
}

async function fetchNbssObject(fid: string, env: Env): Promise<Response> {
  const hex = fid.replace(/^NBSS:/i, "");
  const path = `/nbss/${hex}`;
  if (env.VPC_SERVICE) {
    return env.VPC_SERVICE.fetch(`http://nbss.internal${path}`);
  }
  const nbssBase = (env.NBSS_BASE_URL ?? "").trim().replace(/\/+$/, "");
  if (!nbssBase.startsWith("http")) {
    throw new Error("nbss_not_configured");
  }
  return fetch(`${nbssBase}/${hex}`);
}

async function putNbssObject(content: string, env: Env): Promise<string> {
  const body = utf8Bytes(content);
  if (env.VPC_SERVICE) {
    const response = await env.VPC_SERVICE.fetch("http://nbss.internal/nbss", {
      method: "PUT",
      body
    });
    if (!response.ok) {
      throw new Error(`nbss_put_http_${response.status}`);
    }
    const payload = await response.json() as { fid?: string };
    const fid = asTrimmedString(payload?.fid);
    if (!fid) {
      throw new Error("nbss_put_missing_fid");
    }
    return `NBSS:${fid}`;
  }
  const nbssBase = (env.NBSS_BASE_URL ?? "").trim().replace(/\/+$/, "");
  if (!nbssBase.startsWith("http")) {
    throw new Error("nbss_not_configured");
  }
  const response = await fetch(nbssBase, {
    method: "PUT",
    body
  });
  if (!response.ok) {
    throw new Error(`nbss_put_http_${response.status}`);
  }
  const payload = await response.json() as { fid?: string };
  const fid = asTrimmedString(payload?.fid);
  if (!fid) {
    throw new Error("nbss_put_missing_fid");
  }
  return `NBSS:${fid}`;
}

async function buildDetailItem(
  id: string,
  namespaceId: string,
  hydrateBody: boolean,
  env: Env
): Promise<DetailItem | null> {
  const matches = await env.TEXT_DOCS.getByIds([id]);
  const match = matches[0];
  if (!match) return null;
  const metadata = normalizeMetadata(match.metadata);
  if ((metadata.namespaceId ?? "") !== namespaceId) {
    return null;
  }

  const item: SearchItem = {
    id: match.id,
    score: null,
    rerankScore: null,
    namespaceId: metadata.namespaceId ?? "",
    text: metadata.text ?? "",
    nbssfid: metadata.nbssfid ?? "",
    meta: metadata.meta ?? {}
  };
  await maybeHydrateBody([item], hydrateBody, env);

  return {
    id: item.id,
    namespaceId: item.namespaceId,
    text: item.text,
    bodyText: item.bodyText ?? item.text,
    bodySource: item.bodySource ?? "inline",
    nbssfid: item.nbssfid,
    meta: item.meta
  };
}

async function createNoteRecord(
  namespaceId: string,
  title: string,
  body: string,
  sourceType: string,
  tags: string[],
  autoGenerated: boolean,
  env: Env
): Promise<DetailItem> {
  const id = generateNoteId();
  const createdAt = new Date().toISOString();
  const inlineByteLimit = 8 * 1024;

  let text = body;
  let nbssfid = "";
  if (utf8Bytes(body).byteLength > inlineByteLimit) {
    nbssfid = await putNbssObject(body, env);
    text = truncateUtf8Text(body, inlineByteLimit - 128);
  }

  const cleanTags = sanitizeTags(tags);
  const metadata: TextDocMetadata = {
    text,
    namespaceId,
    nbssfid,
    meta: {
      createdAt,
      docKind: "raw_text",
      sourceType,
      title,
      sourceId: id,
      tags: cleanTags,
      autoGenerated
    }
  };
  const vectorMetadata: Record<string, VectorizeVectorMetadata> = {
    text: metadata.text ?? "",
    namespaceId: metadata.namespaceId ?? "",
    nbssfid: metadata.nbssfid ?? "",
    meta: {
      createdAt: metadata.meta?.createdAt ?? "",
      docKind: metadata.meta?.docKind ?? "",
      sourceType: metadata.meta?.sourceType ?? "",
      title: metadata.meta?.title ?? "",
      sourceId: metadata.meta?.sourceId ?? "",
      tags: cleanTags,
      autoGenerated: metadata.meta?.autoGenerated ?? false
    }
  };

  const embeddingInput = [title, cleanTags.length ? `标签: ${cleanTags.join(", ")}` : "", body]
    .filter(Boolean)
    .join("\n\n");
  const vector = await embedText(embeddingInput, env);
  await env.TEXT_DOCS.upsert([
    {
      id,
      values: vector,
      metadata: vectorMetadata
    }
  ]);

  const item: DetailItem = {
    id,
    namespaceId,
    text,
    bodyText: body,
    bodySource: nbssfid ? "nbss" : "inline",
    nbssfid,
    meta: {
      createdAt,
      docKind: "raw_text",
      sourceType,
      title,
      sourceId: id,
      tags: cleanTags,
      autoGenerated
    }
  };
  try {
    await indexRecentNote(item, env);
  } catch (error) {
    try {
      await env.TEXT_DOCS.deleteByIds([id]);
    } catch (cleanupError) {
      console.error("vector cleanup failed after recent note index failure", {
        id,
        error: cleanupError instanceof Error ? cleanupError.message : String(cleanupError)
      });
    }
    throw new Error(`recent_note_index_write_failed:${error instanceof Error ? error.message : String(error)}`);
  }
  return item;
}

async function handleCreate(request: Request, env: Env): Promise<Response> {
  const payload = await readJson<CreateRequest>(request);
  if (!payload) {
    return json(400, { ok: false, error: "invalid_json" });
  }

  const namespaceId = asTrimmedString(payload.namespaceId ?? env.DEFAULT_NAMESPACE_ID);
  if (!namespaceId) {
    return json(400, { ok: false, error: "missing_namespace_id" });
  }

  const title = asTrimmedString(payload.title);
  const body = typeof payload.body === "string" ? payload.body.trim() : "";
  if (!title) {
    return json(400, { ok: false, error: "missing_title" });
  }
  if (!body) {
    return json(400, { ok: false, error: "missing_body" });
  }

  const item = await createNoteRecord(namespaceId, title, body, "manual_note", [], false, env);

  return json(201, {
    ok: true,
    service: "cfworker-vecdocsrv",
    index: "text-docs",
    item
  });
}

async function handleAutoCreate(request: Request, env: Env): Promise<Response> {
  const payload = await readJson<AutoCreateRequest>(request);
  if (!payload) {
    return json(400, { ok: false, error: "invalid_json" });
  }

  const namespaceId = asTrimmedString(payload.namespaceId ?? env.DEFAULT_NAMESPACE_ID);
  if (!namespaceId) {
    return json(400, { ok: false, error: "missing_namespace_id" });
  }

  const body = typeof payload.body === "string" ? payload.body.trim() : "";
  if (!body) {
    return json(400, { ok: false, error: "missing_body" });
  }

  const generated = await generateAutoNoteMeta(body, env);
  const item = await createNoteRecord(namespaceId, generated.title, body, "semi_auto_note", generated.tags, true, env);
  return json(201, {
    ok: true,
    service: "cfworker-vecdocsrv",
    index: "text-docs",
    item,
    generated: {
      title: item.meta.title ?? "",
      tags: item.meta.tags ?? []
    }
  });
}

async function handleSearch(request: Request, env: Env): Promise<Response> {
  const payload = await readJson<SearchRequest>(request);
  if (!payload) {
    return json(400, { ok: false, error: "invalid_json" });
  }

  const query = String(payload.query ?? "").trim();
  if (!query) {
    return json(400, { ok: false, error: "missing_query" });
  }

  const namespaceId = String(payload.namespaceId ?? env.DEFAULT_NAMESPACE_ID ?? "").trim();
  if (!namespaceId) {
    return json(400, { ok: false, error: "missing_namespace_id" });
  }

  const page = asPositiveInt(payload.page, 1, 50);
  const limit = asPositiveInt(payload.limit ?? env.DEFAULT_RESULT_LIMIT, 10, 20);
  const offset = (page - 1) * limit;
  const desiredCount = offset + limit;
  const requestedVectorLimit = asPositiveInt(payload.vectorLimit ?? env.DEFAULT_VECTOR_LIMIT, 40, 50);
  const vectorLimit = Math.max(requestedVectorLimit, Math.min(Math.max(desiredCount * 4, 40), 50));
  const minRerankScore = asNonNegativeNumber(payload.minRerankScore ?? env.DEFAULT_MIN_RERANK_SCORE, 0.15);
  const bodyMode: BodyMode = payload.bodyMode === "inline" || payload.bodyMode === "nbss" ? payload.bodyMode : "all";
  const hydrateBody = Boolean(payload.hydrateBody);
  const tags = sanitizeTags(payload.tags);

  const queryVector = await embedQuery(query, env);
  const matches = await queryVectorize(queryVector, namespaceId, vectorLimit, env);
  const reranked = await rerankMatches(query, matches, matches.length, env);
  const filtered = reranked.filter((item) =>
    (item.rerankScore ?? 0) >= minRerankScore && matchesBodyMode(item, bodyMode) && matchesTags(item, tags)
  );
  const paged = filtered.slice(offset, offset + limit);
  await maybeHydrateBody(paged, hydrateBody, env);

  return json(200, {
    ok: true,
    service: "cfworker-vecdocsrv",
    index: "text-docs",
    namespaceId,
    query,
    page,
    limit,
    vectorLimit,
    vectorHitCount: matches.length,
    resultCount: paged.length,
    totalCount: filtered.length,
    hasMore: offset + paged.length < filtered.length,
    minRerankScore,
    bodyMode,
    tags,
    models: {
      embedding: EMBED_MODEL,
      reranker: RERANK_MODEL
    },
    items: paged
  });
}

async function handleDetail(request: Request, env: Env, id: string): Promise<Response> {
  const payload = request.method === "POST" ? await readJson<DetailRequest>(request) : null;
  const url = new URL(request.url);
  const namespaceId = String(
    payload?.namespaceId ??
    url.searchParams.get("namespaceId") ??
    env.DEFAULT_NAMESPACE_ID ??
    ""
  ).trim();
  if (!namespaceId) {
    return json(400, { ok: false, error: "missing_namespace_id" });
  }

  const hydrateBody = request.method === "POST"
    ? Boolean(payload?.hydrateBody)
    : isTruthy(url.searchParams.get("hydrateBody") ?? undefined);

  const item = await buildDetailItem(id, namespaceId, hydrateBody, env);
  if (!item) {
    return json(404, { ok: false, error: "not_found" });
  }

  return json(200, {
    ok: true,
    service: "cfworker-vecdocsrv",
    index: "text-docs",
    item
  });
}

async function handleRecent(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const limitValue = url.searchParams.get("limit");
  const result = await listRecentNotes({
    namespaceId: url.searchParams.get("namespaceId") ?? env.DEFAULT_NAMESPACE_ID,
    limit: limitValue ? Number(limitValue) : undefined,
    cursor: url.searchParams.get("cursor") ?? undefined,
    tags: url.searchParams.getAll("tag")
  }, env);

  return json(200, {
    ok: true,
    service: "cfworker-vecdocsrv",
    index: "recent-notes",
    namespaceId: asTrimmedString(url.searchParams.get("namespaceId") ?? env.DEFAULT_NAMESPACE_ID),
    limit: result.limit,
    hasMore: result.hasMore,
    nextCursor: result.nextCursor,
    tags: result.tags,
    items: result.items
  });
}

export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === "GET" && url.pathname === "/healthz") {
      return json(200, {
        ok: true,
        service: "cfworker-vecdocsrv",
        index: "text-docs",
        defaultNamespaceId: env.DEFAULT_NAMESPACE_ID ?? ""
      });
    }

    if (request.method === "POST" && url.pathname === "/api/v1/text-docs/search") {
      try {
        return await handleSearch(request, env);
      } catch (error) {
        console.error("text-doc search failed", error);
        return json(500, {
          ok: false,
          error: "internal_error",
          detail: error instanceof Error ? error.message : String(error)
        });
      }
    }

    if (request.method === "GET" && url.pathname === "/api/v1/text-docs/recent") {
      try {
        return await handleRecent(request, env);
      } catch (error) {
        console.error("text-doc recent failed", error);
        return json(500, {
          ok: false,
          error: "internal_error",
          detail: error instanceof Error ? error.message : String(error)
        });
      }
    }

    if (request.method === "POST" && url.pathname === "/api/v1/text-docs") {
      try {
        return await handleCreate(request, env);
      } catch (error) {
        console.error("text-doc create failed", error);
        return json(500, {
          ok: false,
          error: "internal_error",
          detail: error instanceof Error ? error.message : String(error)
        });
      }
    }

    if (request.method === "POST" && url.pathname === "/api/v1/text-docs/auto") {
      try {
        return await handleAutoCreate(request, env);
      } catch (error) {
        console.error("text-doc auto create failed", error);
        return json(500, {
          ok: false,
          error: "internal_error",
          detail: error instanceof Error ? error.message : String(error)
        });
      }
    }

    const detailMatch = url.pathname.match(/^\/api\/v1\/text-docs\/([^/]+)$/);
    if (detailMatch && (request.method === "GET" || request.method === "POST")) {
      try {
        return await handleDetail(request, env, decodeURIComponent(detailMatch[1]));
      } catch (error) {
        console.error("text-doc detail failed", error);
        return json(500, {
          ok: false,
          error: "internal_error",
          detail: error instanceof Error ? error.message : String(error)
        });
      }
    }

    return json(404, { ok: false, error: "not_found" });
  }
};
